using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.Extensions.Logging;

namespace Chirp.Web.Tests;

/// <summary>
/// Entirely generated by ChatGPT. Used to mute webapp logging in HTMLUnitTests tests.
/// </summary>
public class QuietWebAppFactory<TProgram> : WebApplicationFactory<TProgram>
    where TProgram : class
{
    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        builder.ConfigureLogging(logging =>
        {
            logging.ClearProviders(); // Removes all loggers (Console, Debug, etc.)
            logging.SetMinimumLevel(LogLevel.Error);
        });
    }
}
